### ISSUE TITLE
No responseTemplate was found in the tools schema provided to the client after converting mcp-server. yaml to mcp tools

### ISSUE THREAD

**Issue by leil24** [higress-group/openapi-to-mcpserver#3]
this is my mcp-server.yaml
```yaml
server:
  name: user
tools:
  - name: getUserByName
    description: 根据用户名称获取用户详情 - 根据提供的用户名称获取对应的用户详细信息
    args:
      - name: name
        description: 用户名称
        type: string
        required: true
        position: path
    requestTemplate:
      url: /getUser/{name}
      method: GET
    responseTemplate:
      prependBody: |+
        API Response Information

        Below is the response from an API call. To help you understand the data, I've provided:

        1. A detailed description of all fields in the response structure
        2. The complete API response

        Response Structure

        > Content-Type: application/json

        - **age**: 用户年龄 (Type: integer)
        - **id**: 用户唯一标识 (Type: string)
        - **name**: 用户姓名 (Type: string)

        Original Response`
```

The tools schema received by the client is:
```json
{
  "name": "getUserByName",
  "description": "根据用户名称获取用户详情 - 通过用户名查询对应用户的详细信息（返回JSON字符串）",
  "inputSchema": {
    "properties": {
      "name": {
        "description": "用户名称",
        "type": "string"
      }
    },
    "required": [
      "name"
    ],
    "type": "object"
  }
}
```

The defined responsiveTemplate is discarded when handed over to the client (AI), so how can AI perceive the structure of the response body? So that the AI big model can more accurately call the MCP tool. Is it because the MCP tool in the Python SDK currently does not provide the corresponding ResponseSchema? So is there a compromise solution: describe the responsiveTemplate in the description field, just like how we manually write tools functions to define detailed function comments, including function usage, input and output parameter usage descriptions. The above are my personal opinions and questions. Please answer them for me.
